version: '3.3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ../backend/foodgram/foodgram/.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  web:
    image: wildd/foodgram:latest
    volumes:
      - static_value:/web/foodgram/backend_static/
      - media_value:/web/foodgram/backend_media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/users/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - frontend
      - web

volumes:
  postgres_data:
  static_value:
  media_value: