version: '3.3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ../backend/foodgram/foodgram/.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/users/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - web

volumes:
  postgres_data:
  static_value:
  media_value: