# Generated by Django 3.2.5 on 2021-08-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/recipes/images/noimage.png', upload_to='media/recipes/images/'),
        ),
    ]
