# Generated by Django 3.2.5 on 2021-08-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210720_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
